### ISSUE TITLE
GT rendered images for evaluation

### ISSUE THREAD

**Issue by ymxie97** [zeng-yifei/STAG4D#10]
Hi, Thanks for the great work! 

The evaluation views on the dataset from Consistent4D should be different. Could you please provide the ground truth rendered images for evaluation? 

Thanks!

**Comment by zeng-yifei** [comment]
The render settings we use for the evaluation is actually the same as Consistent4D. We provide the result of ours here if you need. 
[stag4d.zip](https://github.com/user-attachments/files/15580260/stag4d.zip)

**Comment by ymxie97** [comment]
Thanks for you reply! So the evaluated images are after optimization (stage 2) instead of stage 1's output. Another question is why the Consistent4D's LPIPS reported in Table 1 is different from the numbers reported in Consisten4D paper if the evaluation setting is the same?

**Comment by zeng-yifei** [comment]
The view setting is the same, but the frames are not. In our setting, we use 30 frames to run for evaluation, so we rerun the eval script. Consistent4D gets a better LPIPS in this turn, and we don't know the reason too (laugh).  However, we just put the result we tested in this table. That's why Consistent4D's LPIPS is better than the original paper.

**Comment by ymxie97** [comment]
Thanks for your reply! Very appreciate it

**Comment by mengmengliu1998** [comment]
If it would be possible to share the Consistent4D evaluation dataset processed using the following command from your STAG4D paper:
python scripts/gen_mv.py --path dataset/your_data --pipeline_path xxx/guidance/zero123pp
