### ISSUE TITLE
RuntimeError: CUDA error: an illegal instruction was encountered

### ISSUE THREAD

**Issue by 000skysky000** [zeng-yifei/STAG4D#23]
Hello,great work!

      I met a strange illegal memory access error. It happen everytime run:
      
      `python main.py --config configs/stag4d.yaml path=dataset/minions save_path=minions`
      
      when  it try to  loaded zero123!   it give me:

`RuntimeError: CUDA error: an illegal instruction was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions` 

**It may cause by pytorch version and cuda version dismatch.  Can u tell me what version u use ?**
─────────────────────────
my cuda version anda torch version as follow, I use nvidia H800

![图片](https://github.com/user-attachments/assets/d09a87e0-7167-4bcf-9167-04c39e19538d)

![图片](https://github.com/user-attachments/assets/784ce542-5204-4c53-a308-0e80fd9240a4)

the exact output as follow: 
![图片](https://github.com/user-attachments/assets/cf421c85-87ed-448e-9f7f-7879fa0367a6)
![图片](https://github.com/user-attachments/assets/1ba45121-8f15-4ce5-aa3e-45aa51ae644b)
![图片](https://github.com/user-attachments/assets/7a97c310-111f-421c-a658-477038911e7d)

**Comment by 000skysky000** [comment]
It seem to be  a nvidia versions mistake I updated my NVIDIA driver and coda versions to 12.4 . now it's work perfect

**Comment by ScienceLi1125** [comment]
Hi, sorry to bother you. Can you reproduce the project successfully? While trying to reproduce the results using the provided command:
```
python main.py --config configs/stag4d.yaml path=dataset/minions save_path=minions
```

I encountered the following error:
```
RuntimeError: Function 'MseLossBackward0' returned nan values in its 0th output.
```

Upon further investigation, I tracked the loss values and found that the `image_loss` term grows extremely large (around `6.0889e+29`), which eventually causes an overflow. The relevant [line]([https://github.com/zeng-yifei/STAG4D/blob/9aa21c92f40b797c7ee47262609dba3cdd02e861/main.py#L297)](https://github.com/zeng-yifei/STAG4D/blob/9aa21c92f40b797c7ee47262609dba3cdd02e861/main.py#L297)).) in `main.py` appears to be:

```
image_loss = step_ratio * 20000 * F.mse_loss(image, self.input_img_torch)
```

I was wondering if this issue might be caused by improper coefficient settings. Would you happen to know what might be causing this, or if adjusting certain parameters could help?

Additionally, I noticed that in the early stages of training, `image` and `self.input_img_torch` have different sizes. The former is `torch.Size([1, 3, 512, 512])`, as determined by `render_resolution`, while the latter is also `torch.Size([1, 3, 512, 512])`. I am unsure if this discrepancy affects the training process.

I would greatly appreciate any insights or suggestions you could provide. Thank you for your time and consideration—I truly value your guidance!
